export const ACTION_TYPES = Object.freeze({
  GET_VIDEOGAME_DETAIL: "GET_VIDEOGAME_DETAIL",
  GET_VIDEOGAMES: "GET_VIDEOGAMES",
  CLEAN_DETAIL: "CLEAN_DETAIL",
  GET_GENRES: "GET_GENRES",
  ADD_GENRES: "ADD_GENRES",
  ORDER_VIDEOGAMES: "ORDER_VIDEOGAMES",
  GET_VIDEOGAMES_BY_NAME: "GET_VIDEOGAMES_BY_NAME",
  ORDER_VIDEOGAMES: "ORDER_VIDEOGAMES",
  GET_VIDEOGAMES_BY_SOURCE: "GET_VIDEOGAMES_BY_SOURCE",
  GET_VIDEOGAMES_BY_GENRE: "GET_VIDEOGAMES_BY_GENRE",
  SET_SOURCE: "SET_SOURCE",
  SET_ORDER: "SET_ORDER",
  RESET_FILTERS: "RESET_FILTERS",
  SET_RESET_TO_FALSE: "SET_RESET_TO_FALSE",
  SET_SEARCHED: "SET_SEARCHED"
});

export const ENDPOINTS = Object.freeze({
  VIDEOGAMES: "http://localhost:3001/videogames/",
  GENRES: "http://localhost:3001/genres",
  VIDEOGAMES_BY_NAME: "http://localhost:3001/videogames?name="
});
